"""Assemble Stoic Analysis portal HTML and n8n render node code."""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / 'dfa-code' / 'portal'
APP_PARTS = sorted((PORTAL / 'app').glob('*.js'))


def load_app_script() -> str:
    chunks = [path.read_text().strip() for path in APP_PARTS]
    return '\n\n'.join(chunk for chunk in chunks if chunk) + '\n'


def build_portal_html() -> str:
    head = (PORTAL / 'head.html').read_text()
    css = (PORTAL / 'styles.css').read_text()
    markup = (PORTAL / 'markup.html').read_text()
    app_js = load_app_script()
    return ''.join([
        head,
        css,
        '\n</style>\n</head>\n<body>\n',
        markup,
        '<script>\n',
        app_js,
        '</script>\n</body>\n</html>',
    ])


def validate_portal_script(html: str) -> None:
    checker = r"""
const html = process.argv[1];
const m = html.match(/<script>([\s\S]*?)<\/script>/);
if (!m) throw new Error('portal script block missing');
new Function(m[1]);
"""
    subprocess.run(
        ['node', '-e', checker, html],
        check=True,
        capture_output=True,
        text=True,
    )


def build_portal_render_js() -> str:
    html = build_portal_html()
    validate_portal_script(html)
    return (
        '// Generated by scripts/portal_assemble.py — edit dfa-code/portal/ instead\n'
        f'const html = {json.dumps(html)};\n'
        'return [{ json: { html } }];\n'
    )


def write_portal_render(out_path: Path | None = None) -> str:
    code = build_portal_render_js()
    target = out_path or (ROOT / 'dfa-code' / 'portal_render.js')
    target.write_text(code)
    return code


if __name__ == '__main__':
    write_portal_render()
    print('Wrote', ROOT / 'dfa-code' / 'portal_render.js')
